### ISSUE TITLE
Remove inline styling

### ISSUE THREAD

**Issue by mandiwise** [redacademy/evans-spring-2017#12]
Please remove the inline styling from the `page-camp-faq.php` and `page-site-accomodation.php` templates (re: the background image). Please also remove the same inline styling from templates in your `page-templates` dir.

Use the approach that we learned on the About page template in Inhabitent instead.

**Comment by victorsalmon** [comment]
Thanks so much for taking the time to explain how this works! As every page has a hero image, I've removed all inline styles and implemented an evans_lake_hero_img_update() in extras.php and will exclude pages from that style if we add pages that do not have a hero. Fixed in commit b356a38a4fba8f9a7a9a1d6d619264927456ee26.
